services:
  - type: web
    runtime: static
    name: fermi-game
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true # Enable auto-deploy for frontend (this is default, but being explicit)
    routes:
      - type: rewrite
        source: /fermi-game/*
        destination: /*
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.js
        name: Content-Type
        value: application/javascript
    envVars:
      - key: VITE_API_BASE_URL
        value: https://fermi-game.onrender.com # Update after backend is deployed
